// resources/ts/Layouts/Components/Breadcrumb.vue
<template>
    <div>
        <nav v-if="Layout.backLinkOfBreadcrumb?.link" class="sm:hidden" aria-label="Back">
            <a
                :href="Layout.backLinkOfBreadcrumb.link"
                class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700"
            >
                <!-- Heroicon name: solid/chevron-left -->
                <svg
                    class="flex-shrink-0 -ml-1 mr-1 h-5 w-5 text-gray-400"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                    aria-hidden="true"
                >
                    <path
                        fill-rule="evenodd"
                        d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                        clip-rule="evenodd"
                    />
                </svg>
                Back
            </a>
        </nav>
        <nav class="hidden sm:flex" aria-label="Breadcrumb">
            <ol role="list" class="flex items-center space-x-4">
                <li>
                    <div class="flex">
                        <a
                            href="/"
                            class="text-sm font-medium text-gray-500 hover:text-gray-700"
                        >Home</a>
                    </div>
                </li>
                <li v-for="({ label, link }) in Layout.breadcrumb">
                    <div class="flex items-center">
                        <!-- Heroicon name: solid/chevron-right -->
                        <svg
                            class="flex-shrink-0 h-5 w-5 text-gray-400"
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 20 20"
                            fill="currentColor"
                            aria-hidden="true"
                        >
                            <path
                                fill-rule="evenodd"
                                d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                clip-rule="evenodd"
                            />
                        </svg>
                        <a
                            :href="link ? link : 'javascript:void(0);'"
                            class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700"
                        >{{ label }}</a>
                    </div>
                </li>
            </ol>
        </nav>
    </div>
</template>
<script setup>
import { computed } from 'vue';
import { useLayoutStore } from 'VueApp/store';

const Layout = useLayoutStore()
</script>

// resources/react/layouts/AuthLayout/Breadcrumb.tsx
import {Link, useMatches} from 'react-router-dom'
import {HomeIcon} from '@heroicons/react/20/solid'
import {ForwardSlashIcon} from '~/components/icons'

export default function Breadcrumb({pages}: { pages: { name: string, href?: string }[] }) {
  let matches = useMatches()

  function isMatchWithCurrent(uri) {
    return matches.some(({pathname}) => pathname === uri)
  }

  return (
    <nav className="flex" aria-label="Breadcrumb">
      <ol role="list" className="flex items-center space-x-1">
        <li>
          <div>
            <Link to="/app/dashboard" className={`${isMatchWithCurrent('/app/dashboard') ? 'text-slate-900 hover:text-slate-400' : 'text-slate-400 hover:text-slate-900'}`}>
              <HomeIcon className="h-5 w-5 flex-shrink-0" aria-hidden="true"/>
              <span className="sr-only">Home</span>
            </Link>
          </div>
        </li>
        {pages.map((page) => (
          <li key={page.name}>
            <div className="flex items-center">
              <ForwardSlashIcon className="h-5 w-5 flex-shrink-0 text-slate-900"/>
              {page.href ? <>
                <Link to={page.href} className={[isMatchWithCurrent(page.href) ? 'text-slate-900 hover:text-slate-400' : 'text-slate-400 hover:text-slate-900', 'ml-1 text-sm font-medium'].join(' ')} aria-current={isMatchWithCurrent(page.href) ? 'page' : undefined}>
                  {page.name}
                </Link>
              </> : <>
                <span className="ml-1 text-sm font-medium text-slate-900 hover:text-slate-700" aria-current={'page'}>
                  {page.name}
                </span>
              </>}

            </div>
          </li>
        ))}
      </ol>
    </nav>
  )
}
